export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    INCREASE_ITEM_QTY: 'INCREASE_ITEM_QTY',
    DECREASE_ITEM_QTY: 'DECREASE_ITEM_QTY',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART'
};
